
/**
 * Created by yvdedu.com on 2018/2/26.
 */
module.exports = {
	"province": [
		// { "title": "不显示地理位置", "weight": 0, "evaluation_value": 0, "code": "none", "disabled": false },
		{ "title": "A","weight": 1,"evaluation_value": 0, "hint": "", "code": "a","disabled": false },
		{ "title": "B", "weight": 3, "evaluation_value": 0, "hint": "", "code": "b", "disabled": false },
		{ "title": "C", "weight": 5, "evaluation_value": 0, "hint": "", "code": "c", "disabled": false },
		{ "title": "D", "weight": 10, "evaluation_value": 0, "code": "d", "disabled": false },
		{ "title": "E", "weight": 20, "evaluation_value": 0, "code": "e", "disabled": false },
		{ "title": "F", "weight": 30, "evaluation_value": 0, "code": "f", "disabled": false },
		{ "title": "G", "weight": 40, "evaluation_value": 0, "code": "g", "disabled": false },
		{ "title": "H", "weight": 50, "evaluation_value": 0, "code": "h", "disabled": false },
		{ "title": "J", "weight": 70, "evaluation_value": 0, "code": "j", "disabled": false },
		{ "title": "K", "weight": 80, "evaluation_value": 0, "code": "k", "disabled": false },
		{ "title": "L", "weight": 90, "evaluation_value": 0, "code": "l", "disabled": false },
		{ "title": "M", "weight": 100, "evaluation_value": 0, "code": "m", "disabled": false },
		{ "title": "N", "weight": 110, "evaluation_value": 0, "code": "n", "disabled": false },
		{ "title": "P", "weight": 130, "evaluation_value": 0, "code": "p", "disabled": false },
		{ "title": "Q", "weight": 140, "evaluation_value": 0, "code": "q", "disabled": false },
		{ "title": "R", "weight": 150, "evaluation_value": 0, "code": "r", "disabled": false },
		{ "title": "S", "weight": 170, "evaluation_value": 0, "code": "s", "disabled": false },
		{ "title": "T", "weight": 180, "evaluation_value": 0, "code": "t", "disabled": false },
		{ "title": "U", "weight": 190, "evaluation_value": 0, "code": "u", "disabled": false },
		{ "title": "V", "weight": 200, "evaluation_value": 0, "code": "v", "disabled": false },
		{ "title": "W", "weight": 210, "evaluation_value": 0, "code": "w", "disabled": false },
		{ "title": "X", "weight": 220, "evaluation_value": 0, "code": "x", "disabled": false },
		{ "title": "Y", "weight": 230, "evaluation_value": 0, "code": "y", "disabled": false },
		{ "title": "Z", "weight": 240, "evaluation_value": 0, "code": "z", "disabled": false },
		],
	"city": [
		// { "title": "未知城市", "weight": 10, "evaluation_value": 0, "disabled": false, "parent_code": "none" },
		
		{ "title": "安阳", "weight": 20, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "鞍山", "weight": 30, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "安庆", "weight": 40, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "安康", "weight": 50, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "阿坝", "weight": 60, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "阿拉善", "weight": 70, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "阿克苏", "weight": 80, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "阿勒泰", "weight": 90, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		{ "title": "安顺", "weight": 100, "evaluation_value": 0, "disabled": false, "parent_code": "A" },
		
		{ "title": "北京", "weight": 110, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "蚌埠", "weight": 120, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "保定", "weight": 130, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "本溪", "weight": 140, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "包头", "weight": 150, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "亳州", "weight": 160, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "滨州", "weight": 170, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "白城", "weight": 180, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "百色", "weight": 190, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "白山", "weight": 200, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "白银", "weight": 210, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "宝鸡", "weight": 220, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "保山", "weight": 230, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "巴彦淖尔", "weight": 240, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "巴中", "weight": 250, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "北海", "weight": 260, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "毕节", "weight": 270, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "博尔塔拉", "weight": 280, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		{ "title": "巴音郭楞", "weight": 290, "evaluation_value": 0, "disabled": false, "parent_code": "B" },
		
		{ "title": "重庆", "weight": 300, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "成都", "weight": 310, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "长春", "weight": 320, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "长沙", "weight": 330, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "承德", "weight": 340, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "常州", "weight": 350, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "滁州", "weight": 360, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "巢湖", "weight": 370, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "沧州", "weight": 380, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "常德", "weight": 390, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "昌吉", "weight": 400, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "长治", "weight": 410, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "朝阳", "weight": 420, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "潮州", "weight": 430, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "郴州", "weight": 440, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "楚雄", "weight": 450, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "赤峰", "weight": 460, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "池州", "weight": 470, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		{ "title": "崇左", "weight": 480, "evaluation_value": 0, "disabled": false, "parent_code": "C" },
		
		{ "title": "大连", "weight": 490, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "东莞", "weight": 500, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "德州", "weight": 510, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "丹东", "weight": 520, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "大理", "weight": 530, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "大庆", "weight": 540, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "大同", "weight": 550, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "达州", "weight": 560, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "德宏", "weight": 570, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "德阳", "weight": 580, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "定西", "weight": 590, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "迪庆", "weight": 600, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		{ "title": "东营", "weight": 610, "evaluation_value": 0, "disabled": false, "parent_code": "D" },
		
		{ "title": "鄂州", "weight": 620, "evaluation_value": 0, "disabled": false, "parent_code": "E" },
		{ "title": "鄂尔多斯", "weight": 630, "evaluation_value": 0, "disabled": false, "parent_code": "E" },
		{ "title": "恩施", "weight": 640, "evaluation_value": 0, "disabled": false, "parent_code": "E" },
		
		{ "title": "福州", "weight": 650, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "阜阳", "weight": 660, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "佛山", "weight": 670, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "抚州", "weight": 680, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "防城港", "weight": 690, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "抚顺", "weight": 700, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		{ "title": "阜新", "weight": 710, "evaluation_value": 0, "disabled": false, "parent_code": "F" },
		
		{ "title": "广州", "weight": 720, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "贵阳", "weight": 730, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "桂林", "weight": 740, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "赣州", "weight": 750, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "广元", "weight": 760, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "甘孜", "weight": 770, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "广安", "weight": 780, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "贵港", "weight": 790, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		{ "title": "固原", "weight": 800, "evaluation_value": 0, "disabled": false, "parent_code": "G" },
		
		{ "title": "杭州", "weight": 810, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "合肥", "weight": 820, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "哈尔滨", "weight": 830, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "海口", "weight": 840, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "衡阳", "weight": 850, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "邯郸", "weight": 860, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "呼和浩特", "weight": 870, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "黄冈", "weight": 880, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "黄石", "weight": 890, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "湖州", "weight": 900, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "衡水", "weight": 910, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "呼伦贝尔", "weight": 920, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "黄山", "weight": 930, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "海北", "weight": 940, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "海西", "weight": 950, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "哈密", "weight": 960, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "汉中", "weight": 970, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "鹤壁", "weight": 980, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "河池", "weight": 990, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "鹤岗", "weight": 1000, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "黑河", "weight": 1010, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "和田", "weight": 1020, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "河源", "weight": 1030, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "菏泽", "weight": 1040, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "贺州", "weight": 1050, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "红河", "weight": 1060, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "淮安", "weight": 1070, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "淮北", "weight": 1080, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "怀化", "weight": 1090, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "淮南", "weight": 1100, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "惠州", "weight": 1110, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		{ "title": "葫芦岛", "weight": 1120, "evaluation_value": 0, "disabled": false, "parent_code": "H" },
		
		{ "title": "吉林", "weight": 1130, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "济南", "weight": 1140, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "九江", "weight": 1150, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "揭阳", "weight": 1160, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "酒泉", "weight": 1170, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "嘉兴", "weight": 1180, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "荆州", "weight": 1190, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "锦州", "weight": 1200, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "佳木斯", "weight": 1210, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "吉安", "weight": 1220, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "江门", "weight": 1230, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "焦作", "weight": 1240, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "嘉峪关", "weight": 1250, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "金昌", "weight": 1260, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "晋城", "weight": 1270, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "景德镇", "weight": 1280, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "荆门", "weight": 1290, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "金华", "weight": 1300, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "济宁", "weight": 1310, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "晋中", "weight": 1320, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "鸡西", "weight": 1330, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		{ "title": "济源", "weight": 1340, "evaluation_value": 0, "disabled": false, "parent_code": "J" },
		
		{ "title": "昆明", "weight": 1350, "evaluation_value": 0, "disabled": false, "parent_code": "K" },
		{ "title": "开封", "weight": 1360, "evaluation_value": 0, "disabled": false, "parent_code": "K" },
		{ "title": "喀什", "weight": 1370, "evaluation_value": 0, "disabled": false, "parent_code": "K" },
		{ "title": "克拉玛依", "weight": 1380, "evaluation_value": 0, "disabled": false, "parent_code": "K" },
		{ "title": "克孜勒苏", "weight": 1390, "evaluation_value": 0, "disabled": false, "parent_code": "K" },
		
		{ "title": "兰州", "weight": 1400, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "廊坊", "weight": 1410, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "六安", "weight": 1420, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "乐山", "weight": 1430, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "来宾", "weight": 1440, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "柳州", "weight": 1450, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "聊城", "weight": 1460, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "莱芜", "weight": 1470, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "拉萨", "weight": 1480, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "洛阳", "weight": 1490, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "凉山", "weight": 1500, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "连云港", "weight": 1510, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "辽阳", "weight": 1520, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "辽源", "weight": 1530, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "丽江", "weight": 1540, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "临沧", "weight": 1550, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "临汾", "weight": 1560, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "临夏", "weight": 1570, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "临沂", "weight": 1580, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "林芝", "weight": 1590, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "丽水", "weight": 1600, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "六盘水", "weight": 1610, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "陇南", "weight": 1620, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "龙岩", "weight": 1630, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "娄底", "weight": 1640, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "漯河", "weight": 1650, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "泸州", "weight": 1660, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		{ "title": "吕梁", "weight": 1670, "evaluation_value": 0, "disabled": false, "parent_code": "L" },
		
		{ "title": "绵阳", "weight": 1680, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		{ "title": "马鞍山", "weight": 1690, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		{ "title": "茂名", "weight": 1700, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		{ "title": "眉山", "weight": 1710, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		{ "title": "梅州", "weight": 1720, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		{ "title": "牡丹江", "weight": 1730, "evaluation_value": 0, "disabled": false, "parent_code": "M" },
		
		{ "title": "南京", "weight": 1740, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南昌", "weight": 1750, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南宁", "weight": 1760, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "宁波", "weight": 1770, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南通", "weight": 1780, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南充", "weight": 1790, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南平", "weight": 1800, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "南阳", "weight": 1810, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "内江", "weight": 1820, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		{ "title": "宁德", "weight": 1830, "evaluation_value": 0, "disabled": false, "parent_code": "N" },
		
		{ "title": "莆田", "weight": 1840, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "濮阳", "weight": 1850, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "盘锦", "weight": 1860, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "攀枝花", "weight": 1870, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "平顶山", "weight": 1880, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "平凉", "weight": 1890, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "萍乡", "weight": 1900, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		{ "title": "普洱", "weight": 1910, "evaluation_value": 0, "disabled": false, "parent_code": "P" },
		
		{ "title": "青岛", "weight": 1920, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "秦皇岛", "weight": 1930, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "泉州", "weight": 1940, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "衢州", "weight": 1950, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "曲靖", "weight": 1960, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "黔东南", "weight": 1970, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "黔南", "weight": 1980, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "黔西南", "weight": 1990, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "庆阳", "weight": 2000, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "清远", "weight": 2010, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "钦州", "weight": 2020, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "齐齐哈尔", "weight": 2030, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		{ "title": "七台河", "weight": 2040, "evaluation_value": 0, "disabled": false, "parent_code": "Q" },
		
		{ "title": "日照", "weight": 2050, "evaluation_value": 0, "disabled": false, "parent_code": "R" },
		{ "title": "日喀则", "weight": 2060, "evaluation_value": 0, "disabled": false, "parent_code": "R" },
		
		{ "title": "上海", "weight": 2070, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "深圳", "weight": 2080, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "沈阳", "weight": 2090, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "石家庄", "weight": 2100, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "三门峡", "weight": 2110, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "三明", "weight": 2120, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "三亚", "weight": 2130, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "商洛", "weight": 2140, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "商丘", "weight": 2150, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "苏州", "weight": 2160, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "汕头", "weight": 2170, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "汕尾", "weight": 2180, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "十堰", "weight": 2190, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "遂宁", "weight": 2200, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "上饶", "weight": 2210, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "绍兴", "weight": 2220, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "邵阳", "weight": 2230, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "双鸭山", "weight": 2240, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "朔州", "weight": 2250, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "四平", "weight": 2260, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "松原", "weight": 2270, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "绥化", "weight": 2280, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "随州", "weight": 2290, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "宿迁", "weight": 2300, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "宿州", "weight": 2310, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "石嘴山", "weight": 2320, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		{ "title": "韶关", "weight": 2330, "evaluation_value": 0, "disabled": false, "parent_code": "S" },
		
		{ "title": "天津", "weight": 2340, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "太原", "weight": 2350, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "唐山", "weight": 2360, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "台州", "weight": 2370, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "塔城", "weight": 2380, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "泰安", "weight": 2390, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "铁岭", "weight": 2400, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "泰州", "weight": 2410, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "天水", "weight": 2420, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "铜川", "weight": 2430, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "通化", "weight": 2440, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "通辽", "weight": 2450, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "铜陵", "weight": 2460, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "铜仁", "weight": 2470, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		{ "title": "吐鲁番", "weight": 2480, "evaluation_value": 0, "disabled": false, "parent_code": "T" },
		
		{ "title": "武汉", "weight": 2490, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "温州", "weight": 2500, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "无锡", "weight": 2510, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "乌鲁木齐", "weight": 2520, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "芜湖", "weight": 2530, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "潍坊", "weight": 2540, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "威海", "weight": 2550, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "渭南", "weight": 2560, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "文山", "weight": 2570, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "乌海", "weight": 2580, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "乌兰察布", "weight": 2590, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "武威", "weight": 2600, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "吴忠", "weight": 2610, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		{ "title": "梧州", "weight": 2620, "evaluation_value": 0, "disabled": false, "parent_code": "W" },
		
		{ "title": "西安", "weight": 2630, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "厦门", "weight": 2640, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "湘潭", "weight": 2650, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "徐州", "weight": 2660, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "许昌", "weight": 2670, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "信阳", "weight": 2680, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "西宁", "weight": 2690, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "咸阳", "weight": 2700, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "宣城", "weight": 2710, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "新乡", "weight": 2720, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "湘西", "weight": 2730, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "襄阳", "weight": 2740, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "咸宁", "weight": 2750, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "孝感", "weight": 2760, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "锡林郭勒", "weight": 2770, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "兴安", "weight": 2780, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "邢台", "weight": 2790, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "新余", "weight": 2800, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "忻州", "weight": 2810, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "西双版纳", "weight": 2820, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		{ "title": "香港", "weight": 2830, "evaluation_value": 0, "disabled": false, "parent_code": "X" },
		
		{ "title": "扬州", "weight": 2840, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "银州", "weight": 2850, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "银川", "weight": 2860, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "宜昌", "weight": 2870, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "岳阳", "weight": 2880, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "榆林", "weight": 2890, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "烟台", "weight": 2900, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "雅安", "weight": 2910, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "延安", "weight": 2920, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "延安", "weight": 2930, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "延边", "weight": 2940, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "盐城", "weight": 2950, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "阳江", "weight": 2960, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "阳泉", "weight": 2970, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "宜宾", "weight": 2980, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "伊春", "weight": 2990, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "宜春", "weight": 3000, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "伊犁", "weight": 3010, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "营口", "weight": 3020, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "鹰潭", "weight": 3030, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "益阳", "weight": 3040, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "永州", "weight": 3050, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "玉林", "weight": 3060, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "运城", "weight": 3070, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "云浮", "weight": 3080, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		{ "title": "玉溪", "weight": 3090, "evaluation_value": 0, "disabled": false, "parent_code": "Y" },
		
		{ "title": "珠海", "weight": 3100, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "肇庆", "weight": 3110, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "张家口", "weight": 3120, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "中山", "weight": 3130, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "淄博", "weight": 3140, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "驻马店", "weight": 3150, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "枣庄", "weight": 3160, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "张家界", "weight": 3170, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "张掖", "weight": 3180, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "漳州", "weight": 3190, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "湛江", "weight": 3200, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "昭通", "weight": 3210, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "郑州", "weight": 3220, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "镇江", "weight": 3230, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "中卫", "weight": 3240, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "周口", "weight": 3250, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "舟山", "weight": 3260, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "株洲", "weight": 3270, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "自贡", "weight": 3280, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "资阳", "weight": 3290, "evaluation_value": 0, "disabled": false, "parent_code": "Z" },
		{ "title": "遵义", "weight": 3300, "evaluation_value": 0, "disabled": false, "parent_code": "Z" }
		]
};

